version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.9
    commands:
      - pip install cfn-lint

  build:
    commands:
      - pip install -r r53spflat/requirements.txt --target ./r53spflat
      - cfn-lint -t template.yml
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
